In [1]:
import pandas as pd
import numpy as np

In [2]:
# data = pd.read_csv('data/air_quality.csv')
data = pd.read_csv('data/air_quality_cleaned.csv')

# remove null values
# data = data[~data.drop(columns=["Tarih"]).apply(lamda row: row.astype(str).str.contains("-")).any(axis=1)]
# data.to_csv('data/air_quality_cleaned.csv', index=False)

# excel to csv
# data = pd.read_excel('data/air_quality.xlsx')
# data.to_csv('data/air_quality.csv', index=False)

In [3]:

columnsToConvert = [d for d in data.columns if d != "Tarih"]

for col in columnsToConvert:
    data[col] = data[col].str.replace(',', '.', regex=True)  # Virgülleri noktaya çevir
    data[col] = data[col].astype(float)  # Sayıya çevir

data

                    Tarih   PM10  PM2.5   SO2    NO2    NOX     NO
0     2024-01-01 13:00:56  35.45  24.87  3.75  35.02  50.06  15.04
1     2024-01-01 14:00:56  27.26  18.21  4.47  32.62  43.75  11.13
2     2024-01-01 15:00:56  22.97  12.77  4.27  21.22  27.49   6.26
3     2024-01-01 16:00:56  16.65   8.45  4.48  27.62  33.28   5.66
4     2024-01-01 17:00:56  20.90  18.97  3.77  27.88  31.70   3.82
...                   ...    ...    ...   ...    ...    ...    ...
7856  2024-12-31 09:00:56  14.37  15.77  3.07  50.08  57.22   7.14
7857  2024-12-31 10:00:56  17.76  17.07  3.33  47.55  53.51   5.96
7858  2024-12-31 11:00:56  18.08  17.75  3.50  52.15  59.61   7.46
7859  2024-12-31 12:00:56  20.22  16.80  3.18  27.63  29.73   2.10
7860  2024-12-31 13:00:56  12.98  19.84  3.25  37.45  43.37   5.93

[7861 rows x 7 columns]

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7861 entries, 0 to 7860
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Tarih   7861 non-null   object
 1   PM10    7861 non-null   float64
 2   PM2.5   7861 non-null   float64
 3   SO2     7861 non-null   float64
 4   NO2     7861 non-null   float64
 5   NOX     7861 non-null   float64
 6   NO      7861 non-null   float64
dtypes: float64(6), object(1)
memory usage: 430.0+ KB

In [6]:
def calculate_aqi(value, pollutant):
    # PM10 için AQI hesaplama
    if pollutant == 'PM10':
        if value <= 16:
            return (value / 16) * 50
        elif value <= 33:
            return ((value - 16) / (33 - 16)) * (100 - 51) + 51
        elif value <= 50:
            return ((value - 33) / (50 - 33)) * (150 - 101) + 101
        elif value <= 58:
            return ((value - 50) / (58 - 50)) * (200 - 151) + 151
        elif value <= 66:
            return ((value - 58) / (66 - 58)) * (300 - 201) + 201
        else:
            return 500  # 66 µg/m³ ve üstü için AQI 500

    # PM2.5 için AQI hesaplama
    elif pollutant == 'PM2.5':
        if value <= 11:
            return (value / 11) * 50
        elif value <= 23:
            return ((value - 11) / (23 - 11)) * (100 - 51) + 51
        elif value <= 35:
            return ((value - 23) / (35 - 23)) * (150 - 101) + 101
        elif value <= 41:
            return ((value - 35) / (41 - 35)) * (200 - 151) + 151
        elif value <= 47:
            return ((value - 41) / (47 - 41)) * (300 - 201) + 201
        else:
            return 500  # 47 µg/m³ ve üstü için AQI 500

    # SO2 için AQI hesaplama
    elif pollutant == 'SO2':
        if value <= 88:
            return (value / 88) * 50
        elif value <= 177:
            return ((value - 88) / (177 - 88)) * (100 - 51) + 51
        elif value <= 266:
            return ((value - 177) / (266 - 177)) * (150 - 101) + 101
        elif value <= 354:
            return ((value - 266) / (354 - 266)) * (200 - 151) + 151
        elif value <= 443:
            return ((value - 354) / (443 - 354)) * (300 - 201) + 201
        else:
            return 500  # 443 µg/m³ ve üstü için AQI 500

    # NO2 için AQI hesaplama
    elif pollutant == 'NO2':
        if value <= 67:
            return (value / 67) * 50
        elif value <= 134:
            return ((value - 67) / (134 - 67)) * (100 - 51) + 51
        elif value <= 200:
            return ((value - 134) / (200 - 134)) * (150 - 101) + 101
        elif value <= 267:
            return ((value - 200) / (267 - 200)) * (200 - 151) + 151
        elif value <= 334:
            return ((value - 267) / (334 - 267)) * (300 - 201) + 201
        else:
            return 500  # 334 µg/m³ ve üstü için AQI 500

    # NOX için AQI hesaplama
    elif pollutant == 'NOX':
        if value <= 67:
            return (value / 67) * 50
        elif value <= 133:
            return ((value - 67) / (133 - 67)) * (100 - 51) + 51
        elif value <= 200:
            return ((value - 133) / (200 - 133)) * (150 - 101) + 101
        elif value <= 267:
            return ((value - 200) / (267 - 200)) * (200 - 151) + 151
        elif value <= 334:
            return ((value - 267) / (334 - 267)) * (300 - 201) + 201
        else:
            return 500  # 334 µg/m³ ve üstü için AQI 500

    return 0


# Yeni sütun ekleme: AQI
data['AQI'] = data.apply(lambda row: max(
    calculate_aqi(row['PM10'], 'PM10'),
    calculate_aqi(row['PM2.5'], 'PM2.5'),
    calculate_aqi(row['SO2'], 'SO2'),
    calculate_aqi(row['NO2'], 'NO2'),
    calculate_aqi(row['NOX'], 'NOX')
), axis=1)


data

                    Tarih   PM10  PM2.5   SO2    NO2    NOX     NO         AQI
0     2024-01-01 13:00:56  35.45  24.87  3.75  35.02  50.06  15.04  108.635833
1     2024-01-01 14:00:56  27.26  18.21  4.47  32.62  43.75  11.13   83.455294
2     2024-01-01 15:00:56  22.97  12.77  4.27  21.22  27.49   6.26   71.090000
3     2024-01-01 16:00:56  16.65   8.45  4.48  27.62  33.28   5.66   52.873529
4     2024-01-01 17:00:56  20.90  18.97  3.77  27.88  31.70   3.82   83.544167
...                   ...    ...    ...   ...    ...    ...    ...         ...
7856  2024-12-31 09:00:56  14.37  15.77  3.07  50.08  57.22   7.14   70.477500
7857  2024-12-31 10:00:56  17.76  17.07  3.33  47.55  53.51   5.96   75.785833
7858  2024-12-31 11:00:56  18.08  17.75  3.50  52.15  59.61   7.46   78.562500
7859  2024-12-31 12:00:56  20.22  16.80  3.18  27.63  29.73   2.10   74.683333
7860  2024-12-31 13:00:56  12.98  19.84  3.25  37.45  43.37   5.93   87.096667

[7861 rows x 8 columns]

In [36]:
import joblib
from sklearn.model_selection import train_test_split
from sklearn.svm import SVR  
from sklearn.metrics import mean_squared_error
from sklearn.preprocessing import StandardScaler

# Bağımsız (x) ve bağımlı (y) değişkenler
x = data.drop(columns=["Tarih", "AQI"])
y = data["AQI"]

# Veriyi eğitim ve test setlerine ayıralım
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

# Veriyi standartlaştırma
scaler = StandardScaler()
scaler.fit(x_train)
x_train = scaler.transform(x_train)
x_test = scaler.transform(x_test)

# Modeli oluştur ve eğit
# SVR Nedir? https://scikit-learn.org/stable/modules/generated/sklearn.svm.SVR.html 
model = SVR()
model.fit(x_train, y_train)

# Tahmin yap
y_pred = model.predict(x_test)

# Accuracy hesaplama
accuracy = model.score(x_test, y_test)
print("Accuracy:", accuracy)

# Hata hesaplama
mse = mean_squared_error(y_test, y_pred)
print("Mean Squared Error:", mse)

# Test et
test = x_test[0].reshape(1, -1)
print("Predicted AQI:", model.predict(test))
print("Real AQI:", y_test.iloc[0])

# Modeli kaydet
joblib.dump(model, 'models/model.pkl')
joblib.dump(scaler, 'models/scaler.pkl')

Accuracy: 0.7388842755265953
Mean Squared Error: 5048.461031060785
Predicted AQI: [128.74584291]
Real AQI: 116.7664705882353

['models/scaler.pkl']